---
- name: Set modeprob overlay
  shell: modprobe overlay

- name: Set modeprob netfilter
  shell: modprobe br_netfilter

- name: Add k8s GPG apt Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s Repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install k8s
  apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl  